# Generated by Django 5.0.13 on 2025-03-22 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Полное имя')),
                ('email_address', models.EmailField(max_length=255, verbose_name='Электронная почта')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Номер телефона')),
                ('message', models.TextField(blank=True, max_length=255, null=True, verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Заявка клиента',
                'verbose_name_plural': 'Заявки клиентов',
            },
        ),
    ]
