# Generated by Django 5.0.13 on 2025-03-23 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marbell', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='full_name',
        ),
        migrations.AddField(
            model_name='bid',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='bid',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Фамилия'),
        ),
    ]
