# Generated by Django 5.0.13 on 2025-03-23 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marbell', '0002_remove_bid_full_name_bid_first_name_bid_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='first_name',
            field=models.CharField(max_length=255, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='last_name',
            field=models.CharField(max_length=255, verbose_name='Фамилия'),
        ),
    ]
