# Generated by Django 5.0.13 on 2025-03-23 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marbell', '0003_alter_bid_first_name_alter_bid_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название дома')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('prices', models.TextField(blank=True, null=True, verbose_name='Цены')),
                ('mileage', models.TextField(blank=True, null=True, verbose_name='Пробег')),
            ],
            options={
                'verbose_name': 'Дом',
                'verbose_name_plural': 'Дома',
            },
        ),
        migrations.CreateModel(
            name='HousePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='image/%Y/%m/%d', verbose_name='Фотография')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='marbell.house', verbose_name='Дом')),
            ],
            options={
                'verbose_name': 'Фотография дома',
                'verbose_name_plural': 'Фотографии домов',
            },
        ),
    ]
